### PR TITLE
Update STITCH.R to add sessionInfo()

### PR DESCRIPTION
**Pull request by jelber2**
Might be useful for some people otherwise ignore.

### CODE REVIEW

**Comment by rwdavies** [comment]
If I do something like this, I think I would do it from inside the STITCH() command, for consistency between command line and R version running. Is there any particular feature of the sessionInfo() you're particularly interested, or the whole thing?

**Comment by jelber2** [comment]
I guess I just wanted the whole thing just in case I need to report package versions or something like that.

**Comment by jelber2** [comment]
Should I just close the pull request? Like I said, feel free to ignore it.

**Comment by rwdavies** [comment]
Yeah, I think so. I might come back to it at a later point. STITCH has very few dependencies, and what it uses from those are pretty stable, so those are much less likely to be a source of bugs compared to problems within STITCH, so it is probably fine to just have the user know what version they are running and what command they used while running STITCH

**Pull request closed without merging**
